version: 2

jobs:
  build_backend:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Install Dependencies
          command: mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline
      - run:
          name: Run tests
          command: mvn verify
      - persist_to_workspace:
          root: tanaguru-rest/target/
          paths:
            - tanaguru-rest.zip
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_backend:
          filters:
            branches:
              only:
                - develop
                - master